;(function(){
  function k(x){return 'pg_'+x}
  var store={get:function(x){try{return JSON.parse(localStorage.getItem(k(x))||'null')}catch(e){return null}},set:function(x,v){localStorage.setItem(k(x),JSON.stringify(v))}}
  function byId(id){return document.getElementById(id)}
  function val(id){var el=byId(id);return el?el.value.trim():''}
  function ensure(){if(!store.get('profile'))store.set('profile',{});if(!store.get('status'))store.set('status',{courses:[],roles:[],projects:[]});if(!store.get('hobbies'))store.set('hobbies',[]);if(!store.get('logs'))store.set('logs',[]);if(!store.get('theme'))store.set('theme','gufeng')}
  function migrate(){var notes=store.get('notes')||[];if(notes.length){var logs=store.get('logs')||[];notes.forEach(function(nt){var title=(nt.text||'').slice(0,20)||'随想';logs.unshift({date:nt.date||new Date().toISOString().slice(0,10),title:title,desc:nt.text||'',type:'随想',people:'',place:'',tags:nt.tags||[],mood:'平静',energy:3,sensitive:false})});store.set('logs',logs);localStorage.removeItem(k('notes'))}}
  function applyTheme(){var theme=store.get('theme')||'gufeng';document.body.dataset.theme=theme}
  function toggleTheme(){var cur=store.get('theme')||'gufeng';var next=cur==='dark'?'light':'dark';store.set('theme',next);applyTheme()}
  function bindTheme(){var t=byId('theme-toggle');if(t)t.onclick=toggleTheme;applyTheme()}
  function tip(msg){var t=byId('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)};t.textContent=msg;t.style.display='block';clearTimeout(t._to);t._to=setTimeout(function(){t.style.display='none'},1500)}
  function saveProfileFn(){var p=store.get('profile')||{};var exps=p.experiences||[];var v={name:val('pf-name'),langs:val('pf-langs')?val('pf-langs').split(',').map(function(s){return s.trim()}).filter(Boolean):[],social:val('pf-social'),identity:val('pf-identity'),studentLevel:val('pf-stu-level'),studentSeniority:val('pf-stu-seniority'),workerIndustry:val('pf-worker-industry'),workerYears:val('pf-worker-years'),hometown:val('pf-hometown'),experiences:exps};store.set('profile',v);renderProfilePreview();renderUserOverview();renderUserMini()}
  function bindProfile(){var p=store.get('profile')||{};var set=function(id,v){var el=byId(id);if(el)el.value=v||''};set('pf-name',p.name);set('pf-langs',(p.langs||[]).join(', '));set('pf-social',p.social);set('pf-identity',p.identity);set('pf-stu-level',p.studentLevel);set('pf-stu-seniority',p.studentSeniority);set('pf-worker-industry',p.workerIndustry);set('pf-worker-years',p.workerYears||'');set('pf-hometown',p.hometown||'');var exps=(p.experiences||[]);renderExpList(exps);var saveBtn=byId('save-profile');if(saveBtn)saveBtn.onclick=saveProfileFn}
  function renderSimpleList(elId,arr,onDel){var el=byId(elId);if(!el)return;el.innerHTML='';arr.forEach(function(s,i){var li=document.createElement('li');li.textContent=s;var b=document.createElement('button');b.textContent='删除';b.onclick=function(){onDel(i)};li.appendChild(b);el.appendChild(li)})}
  function renderExpList(exps){var list=byId('exp-list');if(!list)return;list.innerHTML='';exps.forEach(function(e,i){var li=document.createElement('li');li.textContent=e.title+' · '+e.period+' · '+e.detail;var b=document.createElement('button');b.textContent='删除';b.onclick=function(){exps.splice(i,1);renderExpList(exps);var p=store.get('profile')||{};p.experiences=exps;store.set('profile',p)};li.appendChild(b);list.appendChild(li)})}
  function bindSpec(){var add=byId('add-spec');if(add)add.onclick=function(){var s=val('spec-input');if(!s)return;var p=store.get('profile')||{};var a=p.specialties||[];a.push(s);p.specialties=a;store.set('profile',p);byId('spec-input').value='';renderSimpleList('spec-list',a,function(i){a.splice(i,1);p.specialties=a;store.set('profile',p);renderSimpleList('spec-list',a)})}}
  function bindExp(){var add=byId('add-exp');if(add)add.onclick=function(){var t=val('exp-title');var pd=val('exp-period');var dt=val('exp-detail');if(!t)return;var p=store.get('profile')||{};var ex=p.experiences||[];ex.push({title:t,period:pd,detail:dt});p.experiences=ex;store.set('profile',p);byId('exp-title').value='';byId('exp-period').value='';byId('exp-detail').value='';renderExpList(ex)
    ;renderProfilePreview();renderUserOverview();tip('已添加经历')
  }}
  function renderHobbies(){var list=byId('hobby-list');if(!list)return;list.innerHTML='';(store.get('hobbies')||[]).forEach(function(h,i){var li=document.createElement('li');var left=document.createElement('div');left.textContent=h.name+' · 技:'+h.skill+' 热:'+h.heat;var tags=document.createElement('div');(h.tags||[]).forEach(function(t){var sp=document.createElement('span');sp.className='tag';sp.textContent=t;tags.appendChild(sp)});var right=document.createElement('div');var del=document.createElement('button');del.textContent='删除';del.onclick=function(){var arr=store.get('hobbies')||[];arr.splice(i,1);store.set('hobbies',arr);renderHobbies();renderProfilePreview()};right.appendChild(del);li.appendChild(left);li.appendChild(tags);li.appendChild(right);list.appendChild(li)})}
  function bindHobby(){var btn=byId('add-hobby');if(btn)btn.onclick=function(){var name=val('hb-name');var skill=parseInt(val('hb-skill')||'0');var heat=parseInt(val('hb-heat')||'0');var tags=val('hb-tags')?val('hb-tags').split(',').map(function(s){return s.trim()}).filter(Boolean):[];if(!name)return;var arr=store.get('hobbies')||[];arr.push({name:name,skill:isNaN(skill)?3:skill,heat:isNaN(heat)?3:heat,tags:tags});store.set('hobbies',arr);byId('hb-name').value='';byId('hb-skill').value='';byId('hb-heat').value='';byId('hb-tags').value='';renderHobbies();renderProfilePreview()}}
  function renderLogs(){var list=byId('log-list');if(!list)return;list.innerHTML='';(store.get('logs')||[]).forEach(function(lg,i){var li=document.createElement('li');var left=document.createElement('div');left.textContent=lg.date+' · '+lg.title+' · '+lg.type;if(lg.sensitive){var bd=document.createElement('span');bd.className='badge';bd.textContent='敏感';bd.style.marginLeft='8px';left.appendChild(bd)}var tags=document.createElement('div');(lg.tags||[]).forEach(function(t){var sp=document.createElement('span');sp.className='tag';sp.textContent=t;tags.appendChild(sp)});var right=document.createElement('div');var del=document.createElement('button');del.textContent='删除';del.onclick=function(){var arr=store.get('logs')||[];arr.splice(i,1);store.set('logs',arr);renderLogs();renderSummary();renderProfilePreview();renderTimeline()};right.appendChild(del);li.appendChild(left);li.appendChild(tags);li.appendChild(right);list.appendChild(li)})}
  function bindLog(){var btn=byId('add-log');if(btn)btn.onclick=function(){var date=val('lg-date')||todayLocal();var title=val('lg-title');var desc=val('lg-desc');var type=val('lg-type');var people=val('lg-people');var place=val('lg-place');var tags=val('lg-tags')?val('lg-tags').split(',').map(function(s){return s.trim()}).filter(Boolean):[];var mood=val('lg-mood');var energy=parseInt(val('lg-energy')||'3');var sensitive=(byId('lg-sensitive')&&byId('lg-sensitive').checked)||false;if(!title)return;var arr=store.get('logs')||[];arr.unshift({date:date,title:title,desc:desc,type:type,people:people,place:place,tags:tags,mood:mood,energy:energy,sensitive:sensitive});store.set('logs',arr);byId('lg-title').value='';byId('lg-desc').value='';byId('lg-people').value='';byId('lg-place').value='';byId('lg-tags').value='';byId('lg-energy').value='';if(byId('lg-sensitive'))byId('lg-sensitive').checked=false;renderLogs();renderSummary();renderProfilePreview();renderTimeline();tip('已添加事件')}}
  function renderStatus(){var st=store.get('status')||{courses:[],roles:[],projects:[]};renderSimpleList('course-list',st.courses,function(i){st.courses.splice(i,1);store.set('status',st);renderStatus()});renderSimpleList('role-list',st.roles,function(i){st.roles.splice(i,1);store.set('status',st);renderStatus()});var pl=byId('project-list');if(pl){pl.innerHTML='';(st.projects||[]).forEach(function(p,i){var li=document.createElement('li');li.textContent=p.name+' · '+p.desc;var b=document.createElement('button');b.textContent='删除';b.onclick=function(){st.projects.splice(i,1);store.set('status',st);renderStatus()};li.appendChild(b);pl.appendChild(li)})}}
  function renderGoals(){var list=byId('goal-list');if(!list)return;list.innerHTML='';(store.get('goals')||[]).forEach(function(g,i){var li=document.createElement('li');var left=document.createElement('div');left.textContent=g.topic+' · 目标:'+g.target+' · 截止:'+g.deadline;var progressWrap=document.createElement('div');progressWrap.className='progress';progressWrap.setAttribute('aria-label','目标进度');progressWrap.setAttribute('role','progressbar');progressWrap.setAttribute('aria-valuemin','0');progressWrap.setAttribute('aria-valuemax','100');progressWrap.style.touchAction='none';var bar=document.createElement('div');bar.className='progress-bar';var cur=Math.max(0,Math.min(100,parseInt(g.progress||0)));bar.style.width=(cur+'%');progressWrap.setAttribute('aria-valuenow',String(cur));progressWrap.appendChild(bar);var range=document.createElement('input');range.type='range';range.min='0';range.max='100';range.step='1';range.value=String(cur);range.className='goal-range';range.setAttribute('aria-label','调整进度');range.style.marginLeft='8px';range.style.width='140px';var dragging=false;var commit=function(pct){var arr=store.get('goals')||[];if(arr[i]){arr[i].progress=pct;store.set('goals',arr)};renderGoals();renderSummary();renderProfilePreview()};var updateByClientX=function(clientX){var rect=progressWrap.getBoundingClientRect();var pct=Math.round(((clientX-rect.left)/rect.width)*100);pct=Math.max(0,Math.min(100,pct));bar.style.width=pct+'%';progressWrap.setAttribute('aria-valuenow',String(pct));range.value=String(pct)};progressWrap.addEventListener('pointerdown',function(e){dragging=true;updateByClientX(e.clientX)});progressWrap.addEventListener('pointermove',function(e){if(!dragging)return;updateByClientX(e.clientX)});progressWrap.addEventListener('pointerup',function(e){dragging=false;var rect=progressWrap.getBoundingClientRect();var pct=Math.round(((e.clientX-rect.left)/rect.width)*100);pct=Math.max(0,Math.min(100,pct));commit(pct)});progressWrap.addEventListener('pointerleave',function(){dragging=false});range.addEventListener('input',function(){var v=parseInt(range.value||'0');v=isNaN(v)?0:Math.max(0,Math.min(100,v));bar.style.width=v+'%';progressWrap.setAttribute('aria-valuenow',String(v));commit(v)});var right=document.createElement('div');var b=document.createElement('button');b.textContent='删除';b.onclick=function(){var arr=store.get('goals')||[];arr.splice(i,1);store.set('goals',arr);renderGoals();renderSummary();renderProfilePreview()};right.appendChild(b);li.appendChild(left);li.appendChild(progressWrap);li.appendChild(range);li.appendChild(right);list.appendChild(li)})}
  function bindStatus(){var addC=byId('add-course');if(addC)addC.onclick=function(){var s=val('course-input');if(!s)return;var st=store.get('status')||{courses:[],roles:[],projects:[]};st.courses.push(s);store.set('status',st);byId('course-input').value='';renderStatus();renderProfilePreview();tip('已添加课程')};var addR=byId('add-role');if(addR)addR.onclick=function(){var s=val('role-input');if(!s)return;var st=store.get('status')||{courses:[],roles:[],projects:[]};st.roles.push(s);store.set('status',st);byId('role-input').value='';renderStatus();renderProfilePreview();tip('已添加职务')};var addP=byId('add-project');if(addP)addP.onclick=function(){var n=val('project-name');var d=val('project-desc');if(!n)return;var st=store.get('status')||{courses:[],roles:[],projects:[]};var ps=st.projects||[];ps.push({name:n,desc:d,tags:[]});st.projects=ps;store.set('status',st);byId('project-name').value='';byId('project-desc').value='';renderStatus();renderProfilePreview();tip('已添加项目')}}
  function bindGoal(){var slider=byId('gl-progress');var out=byId('gl-progress-out');if(slider&&out){var upd=function(){var v=parseInt(slider.value||'0');out.textContent=(isNaN(v)?0:v)+'%'};slider.addEventListener('input',upd);slider.addEventListener('change',upd);upd()}var addG=byId('add-goal');if(addG)addG.onclick=function(){var topic=val('gl-topic');var target=val('gl-target');var deadline=val('gl-deadline')||todayLocal();var progress=parseInt(val('gl-progress')||'0');if(!topic)return;var arr=store.get('goals')||[];arr.push({topic:topic,target:target,deadline:deadline,progress:isNaN(progress)?0:progress});store.set('goals',arr);byId('gl-topic').value='';byId('gl-target').value='';byId('gl-deadline').value='';byId('gl-progress').value='0';if(out)out.textContent='0%';renderGoals();renderSummary();renderProfilePreview();tip('已添加目标')}}
  function pickRecentLogs(days){var d=typeof days==='number'?days:14;var logs=store.get('logs')||[];return logs.filter(function(l){return !l.sensitive && isWithinDays(l.date,d)}).slice(0,5)}
  function topHobbies(){var h=store.get('hobbies')||[];return h.slice().sort(function(a,b){var r=b.heat-a.heat;return r!==0?r:b.skill-a.skill}).slice(0,3)}
  function activeGoals(){var g=store.get('goals')||[];return g.filter(function(x){return x.progress<100}).slice(0,3)}
  function clip(s,max){var m=parseInt(max||'0');if(!m||s.length<=m)return s;return s.slice(0,m)}
  function pad2(n){return (n<10?'0':'')+n}
  function todayLocal(){var now=new Date();return now.getFullYear()+"-"+pad2(now.getMonth()+1)+"-"+pad2(now.getDate())}
  function parseDateLocal(str){if(!str)return new Date(NaN);var p=str.split('-');var y=parseInt(p[0]||'0',10),m=parseInt(p[1]||'1',10),d=parseInt(p[2]||'1',10);return new Date(y,m-1,d)}
  function startOfDayTs(str){var dt=parseDateLocal(str);return new Date(dt.getFullYear(),dt.getMonth(),dt.getDate()).getTime()}
  function isWithinDays(str,days){var ts=startOfDayTs(str);if(isNaN(ts))return false;var diff=Math.abs(Date.now()-ts);return diff<=days*86400000}
  function genIntro(params){var p=store.get('profile')||{};var st=store.get('status')||{courses:[],roles:[],projects:[]};var logs=pickRecentLogs(14);var hobbies=topHobbies();var goals=activeGoals();var name=p.name||'';var hometown=p.hometown||'';var identity=p.identity||'';var lvl=p.studentLevel||'';var sen=p.studentSeniority||'';var industry=p.workerIndustry||'';var years=p.workerYears||'';var hobbyStr=hobbies.map(function(h){return h.name}).join('、');var recent=logs.map(function(l){return l.title}).join('、');var goalStr=goals.map(function(g){return g.topic}).join('、');var course=st.courses[0]||'';var role=st.roles[0]||'';var project=(st.projects[0]&&st.projects[0].name)||'';var specs=(p.specialties||[]);var specStr=(specs[0]||'');var exps=(p.experiences||[]);var expStr=exps.slice(0,2).map(function(e){return e.title}).join('、');var sj=JSON.parse(localStorage.getItem('sj_records')||'null')||[];var sjTagCount={};sj.slice(0,20).forEach(function(r){(r.tags||[]).forEach(function(t){sjTagCount[t]=(sjTagCount[t]||0)+1})});var sjHotArr=Object.keys(sjTagCount).sort(function(a,b){return sjTagCount[b]-sjTagCount[a]}).slice(0,3);var sjHot=sjHotArr.join('、');var scene=params.scene;var tone=params.tone;var length=params.length||'100';var lang=params.lang||'zh';var intro='';if(lang==='zh'){if(scene==='求职'){intro='我叫'+name+'，来自'+(hometown||'')+'。'+(identity==='学生'?'目前就读'+lvl+'，'+(sen||'')+'；':(industry?('从事'+industry+(years?(' '+years+'年'):'')+'。'):''))+'近期在做'+(project||recent)+'，也关注'+(course||hobbyStr)+'。'+(specStr?('特长：'+specStr+'。'):'')+(expStr?('经历：'+expStr+'。'):'')+'当前目标是'+(goalStr||'自我提升')+'。'+(sjHot?('近期关注：'+sjHot+'。'):'')}else if(scene==='Meetup'||scene==='朋友聚餐'){intro='嗨，我是'+name+'，'+(identity||'')+'，来自'+(hometown||'')+'。最近在'+(project||course||'探索')+'，平时喜欢'+(hobbyStr||'阅读/运动')+'，也在'+(role||'参与一些活动')+'。'+(specStr?('我擅长'+specStr+'。'):'')+(sjHot?('最近常聊：'+sjHot+'。'):'')}else{intro='大家好，我是'+name+'，'+(identity||'')+'。近期亮点：'+(project||recent)+'；爱好：'+(hobbies.slice(0,2).map(function(h){return h.name}).join('、')||hobbyStr)+'；'+(specStr?('特长：'+specStr+'；'):'')+(sjHot?('关注：'+sjHot+'；'):'')}}else{var enParts=[];enParts.push("Hi, I'm "+name+(hometown?", from "+hometown:""));if(identity==='学生'){enParts.push("Currently in "+lvl+".")}else if(industry){enParts.push("Working in "+industry+(years?(" for "+years+" years"):"")+".")}enParts.push("Recently on "+(project||recent)+", and into "+(course||hobbyStr)+".");if(specStr)enParts.push("Strength: "+specStr+".");if(goalStr)enParts.push("Goals: "+goalStr+".");if(sjHot)enParts.push("Focus: "+sjHot+".");intro=enParts.join(' ')}if(tone==='专业'){intro=intro+'我关注可度量的产出与协作效率。'}if(tone==='亲和'){intro=intro+'很期待认识同样爱好的朋友。'}if(tone==='随和'){intro=intro+'有缘就聊，轻松一点。'}return clip(intro,parseInt(length))}
  function genTopics(params){var lang=params.lang||'zh';var st=store.get('status')||{courses:[],roles:[],projects:[]};var hobbies=topHobbies();var logs=pickRecentLogs(14);var topics=[];var project=(st.projects[0]&&st.projects[0].name)||'';var course=st.courses[0]||'';var role=st.roles[0]||'';var p=store.get('profile')||{};var specs=(p.specialties||[]);var sj=JSON.parse(localStorage.getItem('sj_records')||'null')||[];var sjTagCount={};sj.slice(0,20).forEach(function(r){(r.tags||[]).forEach(function(t){sjTagCount[t]=(sjTagCount[t]||0)+1})});var sjHot=Object.keys(sjTagCount).sort(function(a,b){return sjTagCount[b]-sjTagCount[a]}).slice(0,2);
    if(project)topics.push(lang==='zh'?'我最近在做'+project+'，你会怎么展开这个方向？':'I am working on '+project+', how would you approach it?');
    if(course)topics.push(lang==='zh'?'这门课程里你觉得最难的点是什么？':'What is the trickiest part of this course for you?');
    if(role)topics.push(lang==='zh'?'你在类似的职务上有什么经验？':'What experience do you have in a similar role?');
    if(hobbies[0])topics.push(lang==='zh'?'最近在折腾'+hobbies[0].name+'，你也感兴趣吗？':'Been into '+hobbies[0].name+' lately, are you into it?');
    if(specs[0])topics.push(lang==='zh'?'我在'+specs[0]+'方面积累了一些经验，要不要交流？':'I have some experience in '+specs[0]+', want to chat?');
    if(sjHot[0])topics.push(lang==='zh'?('近期关注 '+sjHot[0]+'，你怎么看？'):("Lately focused on "+sjHot[0]+", what's your take?"));
    if(logs[0])topics.push(lang==='zh'?'围绕'+logs[0].title+'我学到了一些教训，愿意交流吗？':'I learned some lessons from '+logs[0].title+', want to discuss?');
    return topics.slice(0,5)}
  function aiEnhance(text,params){
    var lang=(params&&params.params&&params.params.lang)||'zh';
    var tone=(params&&params.params&&params.params.tone)||'';
    var onDone=(params&&params.onDone)||function(){};
    var lines=(text||'').split('\n');
    var blankIdx=lines.indexOf('');
    var introLines=[],topicLines=[];
    if(blankIdx>=0){introLines=lines.slice(0,blankIdx);topicLines=lines.slice(blankIdx+1).filter(function(l){return /^\d+\.\s/.test(l)})}else{introLines=[lines.join(' ')]}
    var introText=introLines.join(' ').trim();
    var topics=topicLines.map(function(l){return l.replace(/^\d+\.\s*/,'').trim()}).filter(Boolean);
    var polishedIntro=(lang==='zh'?polishZhIntro(introText,tone):polishEnIntro(introText,tone));
    var topicsPara=topics.length?(lang==='zh'?polishTopicsZh(topics,tone):polishTopicsEn(topics,tone)):'';
    var finalText=polishedIntro+(topicsPara?('\n\n'+topicsPara):'');
    if(topics.length){finalText+='\n\n备选话题：\n'+topics.map(function(t,i){return (i+1)+'. '+t}).join('\n')}
    try{
      var ep=localStorage.getItem('pg_ai_endpoint');
      var key=localStorage.getItem('pg_ai_key');
      if(ep&&key){
        var ctrl=(params&&params.ctrl)||new AbortController();
        var to=setTimeout(function(){ctrl.abort()},8000);
        fetch(ep,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({input:finalText,language:lang,tone:tone,style:'paragraph',length:String((params&&params.params&&params.params.length)||'100'),topics:topics,hints:{avoid:'列表化、句式重复',prefer:'口语化连接词、自然停顿'}}),signal:ctrl.signal}).then(function(r){
          var ct=r.headers.get('content-type')||'';
          if(ct.indexOf('text/event-stream')>=0 && r.body){
            var reader=r.body.getReader();
            var dec=new TextDecoder();
            var acc='';
            var pump=function(){reader.read().then(function(chunk){if(chunk.done){clearTimeout(to);onDone();return}acc+=dec.decode(chunk.value,{stream:true});var parts=acc.split('\n');var last=parts.pop();parts.forEach(function(line){var m=line.match(/^data:\s*(.*)$/);if(m){try{var obj=JSON.parse(m[1]);var out=byId('gen-output');if(out && obj && obj.text){out.textContent=obj.text}}catch(e){}}});acc=last;pump()}).catch(function(){clearTimeout(to);onDone()})};pump();
          }else{
            return r.json().then(function(data){clearTimeout(to);var refined=(data&&data.text)||finalText;var out=byId('gen-output');if(out)out.textContent=refined;onDone()})
          }
        }).catch(function(){clearTimeout(to);onDone()})
      }else{onDone()}
    }catch(e){onDone()}
    return finalText
  }
  function polishZhIntro(s,t){var x=s||'';x=x.replace(/我叫/g,'我是');x=x.replace(/嗨，?我是/g,'我是');x=x.replace(/近期在做/g,'最近专注于');x=x.replace(/最近在/g,'最近在');x=x.replace(/也关注/g,'同时关注');x=x.replace(/也在/g,'也在');x=x.replace(/；/g,'，');x=x.replace(/；/g,'，');x=x.replace(/，\s*。/g,'。');x=x.trim();if(!/[。！？]$/.test(x))x=x+'。';if(t==='文雅（古风）'){x=x.replace(/我是/g,'在下').replace(/最近/g,'近来').replace(/同时/g,'并且').replace(/目标是/g,'所定之目标为')}return x}
  function polishEnIntro(s,t){var x=s||'';x=x.replace(/Hi, I'm/g,"I'm").replace(/Recently on/g,'Recently focused on').replace(/Goals:/g,'My goals:');x=x.replace(/;\s*/g,'. ').replace(/\s*\./g,'.');x=x.trim();if(!/[\.\!?]$/.test(x))x=x+'.';return x}
  function polishTopicsZh(arr,t){var a=arr.slice(0,5);var lead=(t==='文雅（古风）'?'我们不妨从':''||'我们可以聊聊');var join=a.join('、');var s=(t==='文雅（古风）'?lead+' '+join+'。':lead+' '+join+'。');return s}
  function polishTopicsEn(arr,t){var a=arr.slice(0,5);var s='We could also chat about '+a.join(', ')+'.';return s}
  function bindGen(){var btn=byId('generate');if(!btn)return;btn.onclick=function(){var params={scene:val('gen-scene'),tone:val('gen-tone'),length:(byId('gen-length')?val('gen-length'):'100'),lang:(byId('gen-lang')?val('gen-lang'):'zh')};var includeSensitive=byId('gen-include-sensitive')&&byId('gen-include-sensitive').checked;var aiOn=true;if(byId('gen-ai'))aiOn=byId('gen-ai').checked;var intro=genIntro(params);var topics=genTopics({lang:params.lang});var text=intro+'\n\n'+topics.map(function(t,i){return (i+1)+'. '+t}).join('\n');text=aiOn?aiEnhance(text,{includeSensitive:includeSensitive,params:params}):text;var out=byId('gen-output');out.textContent=text;renderSources(params);renderProfilePreview();try{localStorage.setItem('pg_last_generated',JSON.stringify({text:text,params:params,time:Date.now()}));var srcEl=byId('source-details');var srcLines=(srcEl&&srcEl.textContent)?srcEl.textContent.split('\n'):[];localStorage.setItem('pg_last_sources',JSON.stringify(srcLines))}catch(e){}tip('已生成')}}
  var _genCtrl=null;var _genRunning=false;
  function bindGen(){var btn=byId('generate');var cancel=byId('cancel-generate');if(!btn)return;btn.onclick=function(){if(_genRunning)return;var params={scene:val('gen-scene'),tone:val('gen-tone'),length:(byId('gen-length')?val('gen-length'):'100'),lang:(byId('gen-lang')?val('gen-lang'):'zh')};var includeSensitive=byId('gen-include-sensitive')&&byId('gen-include-sensitive').checked;var aiOn=true;if(byId('gen-ai'))aiOn=byId('gen-ai').checked;var intro=genIntro(params);var topics=genTopics({lang:params.lang});var text=intro+'\n\n'+topics.map(function(t,i){return (i+1)+'. '+t}).join('\n');var out=byId('gen-output');out.textContent=aiOn?aiEnhance(text,{includeSensitive:includeSensitive,params:params,ctrl:(_genCtrl=new AbortController()),onDone:function(){_genRunning=false;btn.disabled=false;btn.textContent='生成';if(cancel)cancel.style.display='none'}}):text;renderSources(params);renderProfilePreview();try{localStorage.setItem('pg_last_generated',JSON.stringify({text:out.textContent,params:params,time:Date.now()}));var srcEl=byId('source-details');var srcLines=(srcEl&&srcEl.textContent)?srcEl.textContent.split('\n'):[];localStorage.setItem('pg_last_sources',JSON.stringify(srcLines))}catch(e){}if(aiOn){_genRunning=true;btn.disabled=true;btn.textContent='生成中…';if(cancel){cancel.style.display='inline-block';cancel.onclick=function(){if(_genCtrl){_genCtrl.abort()}_genRunning=false;btn.disabled=false;btn.textContent='生成';cancel.style.display='none'}}}tip('已生成')}}
  function bindOpenShare(){var btn=byId('open-share');if(btn)btn.onclick=function(){window.open('share.html','_blank')}}
  function renderProfilePreview(){var p=store.get('profile')||{};var st=store.get('status')||{courses:[],roles:[],projects:[]};var h=store.get('hobbies')||[];var g=store.get('goals')||[];var logs=pickRecentLogs(14);var el=byId('profile-preview');if(!el)return;var lines=[];lines.push('基本信息：'+[(p.name||''),(p.identity||''),(p.studentLevel||''),(p.studentSeniority||''),(p.hometown||''),(p.social||''),(p.langs||[]).join('/')].filter(Boolean).join(' · '));if(st.courses.length)lines.push('课程：'+st.courses.join('、'));if(st.roles.length)lines.push('职务：'+st.roles.join('、'));if(st.projects.length)lines.push('项目：'+st.projects.map(function(x){return x.name}).join('、'));if((p.experiences||[]).length)lines.push('经历：'+(p.experiences||[]).map(function(e){var extra=[e.period||'',e.detail||''].filter(Boolean).join('；');return e.title+(extra?('（'+extra+'）'):'')}).join('、'));if((p.specialties||[]).length)lines.push('特长：'+(p.specialties||[]).join('、'));if(h.length)lines.push('爱好：'+h.map(function(x){var tag=(x.tags||[]).length?('，'+(x.tags||[]).join('/')):'';return x.name+'(技'+(x.skill||0)+'/热'+(x.heat||0)+tag+')'}).join('、'));if(g.length)lines.push('目标：'+g.map(function(x){var extra=[x.target||'',('进度'+(x.progress||0)+'%'),(x.deadline?('截止'+x.deadline):'')].filter(Boolean).join('；');return x.topic+(extra?('（'+extra+'）'):'')}).join('、'));if(logs.length)lines.push('近期事件：'+logs.map(function(l){return l.title}).join('、'));
    var sj=JSON.parse(localStorage.getItem('sj_records')||'null')||[];if(sj.length){var sjTop=sj.slice(0,5).map(function(r){return r.date+' · '+r.content.slice(0,20)}).join('、');var sjTagCount={};sj.forEach(function(r){(r.tags||[]).forEach(function(t){sjTagCount[t]=(sjTagCount[t]||0)+1})});var hot=Object.keys(sjTagCount).sort(function(a,b){return sjTagCount[b]-sjTagCount[a]}).slice(0,5).join('、');lines.push('成长札记：'+sjTop);lines.push('札记标签TOP：'+hot)}
    el.textContent=lines.join('\n')}
  function renderSources(params){var st=store.get('status')||{courses:[],roles:[],projects:[]};var h=topHobbies();var logs=pickRecentLogs(14);var g=activeGoals();var p=store.get('profile')||{};var el=byId('source-details');if(!el)return;var items=[];if(st.projects[0])items.push('项目：'+st.projects[0].name);if(st.courses[0])items.push('课程：'+st.courses[0]);if(st.roles[0])items.push('职务：'+st.roles[0]);if(h[0])items.push('爱好：'+h[0].name);if((p.specialties||[])[0])items.push('特长：'+(p.specialties||[])[0]);var sj=JSON.parse(localStorage.getItem('sj_records')||'null')||[];if(sj.length){var sjTagCount={};sj.forEach(function(r){(r.tags||[]).forEach(function(t){sjTagCount[t]=(sjTagCount[t]||0)+1})});var hot=Object.keys(sjTagCount).sort(function(a,b){return sjTagCount[b]-sjTagCount[a]}).slice(0,1)[0];if(hot)items.push('札记标签：'+hot)}if(logs[0])items.push('近期事件：'+logs[0].title);if(g[0])items.push('目标：'+g[0].topic);el.textContent=items.join('\n')}
  function computeSummary(){var logs=store.get('logs')||[];var recent=logs.filter(function(l){return isWithinDays(l.date,7)});var countByType={};var countMood={};var tagCount={};recent.forEach(function(l){countByType[l.type]=(countByType[l.type]||0)+1;countMood[l.mood]=(countMood[l.mood]||0)+1;(l.tags||[]).forEach(function(t){tagCount[t]=(tagCount[t]||0)+1})});var topTags=Object.keys(tagCount).map(function(t){return [t,tagCount[t]]}).sort(function(a,b){return b[1]-a[1]}).slice(0,5).map(function(x){return x[0]+'('+x[1]+')'}).join('、');var lines=[];lines.push('近7天事件：'+recent.length);var typeStr=Object.keys(countByType).map(function(k){return k+countByType[k]}).join('、');lines.push('类型分布：'+(typeStr||'无'));var moodStr=Object.keys(countMood).map(function(k){return k+countMood[k]}).join('、');lines.push('心情分布：'+(moodStr||'无'));lines.push('高频标签：'+(topTags||'无'));return lines.join('\n')}
  function renderSummary(){var el=byId('summary-output');if(el)el.textContent=computeSummary();renderStatsBar()}
  function renderStatsBar(){var el=byId('stats-bar');if(!el)return;var sum=computeSummary();var parts=sum.split('\n');var recent=(parts[0]||'').replace(/[^0-9]/g,'');var typeLine=parts[1]||'';var moodLine=parts[2]||'';var tagsLine=parts[3]||'';var tagStr=(tagsLine.split('：')[1]||'').trim();var first=(tagStr.split('、')[0]||'').replace(/\(\d+\)/,'');el.innerHTML='';var mk=function(text){var sp=document.createElement('span');sp.className='badge';sp.textContent=text;return sp};el.appendChild(mk('近7天事件 '+(recent||'0')));if(first)el.appendChild(mk('高频 '+first));if(typeLine)el.appendChild(mk(typeLine));if(moodLine)el.appendChild(mk(moodLine))}
  function renderUserMini(){var el=byId('user-mini');if(!el)return;var p=store.get('profile')||{};el.textContent=p.name||'我';el.onclick=function(){var u=byId('user-overview');if(u){u.scrollIntoView({behavior:'smooth'})}}}
  function renderUserOverview(){var p=store.get('profile')||{};var sumEl=byId('user-summary');if(sumEl){sumEl.innerHTML='';var frag=document.createDocumentFragment();var mk=function(label,value){var div=document.createElement('div');div.className='output';div.textContent=label+'：'+(value||'');return div};frag.appendChild(mk('姓名',p.name||'匿名'));frag.appendChild(mk('身份',p.identity||''));frag.appendChild(mk('语言',(p.langs||[]).join('/')));frag.appendChild(mk('家乡',p.hometown||''));if(p.social)frag.appendChild(mk('社交偏好',p.social));sumEl.appendChild(frag)}var btn=byId('edit-profile-btn');if(btn)btn.onclick=function(){var d=byId('profile-details');if(d){d.open=true;try{d.scrollIntoView({behavior:'smooth'})}catch(e){}}};var stEl=byId('user-stats');if(stEl){var sum=computeSummary();var parts=sum.split('\n');stEl.innerHTML='';parts.forEach(function(line){var sp=document.createElement('span');sp.className='badge';sp.textContent=line;stEl.appendChild(sp)})}}
  function renderTimeline(){var wrap=byId('timeline');if(!wrap)return;wrap.innerHTML='';var logs=store.get('logs')||[];var items=logs.filter(function(l){var ts=startOfDayTs(l.date);return !l.sensitive && !isNaN(ts)});items.sort(function(a,b){return startOfDayTs(b.date)-startOfDayTs(a.date)});items=items.slice(0,10);items.forEach(function(lg,i){var li=document.createElement('div');li.className='timeline-item';var left=document.createElement('div');left.className='meta';left.textContent=lg.date+' · '+lg.type;var main=document.createElement('div');main.textContent=lg.title;var tags=document.createElement('div');(lg.tags||[]).forEach(function(t){var sp=document.createElement('span');sp.className='tag';sp.textContent=t;tags.appendChild(sp)});var right=document.createElement('div');var del=document.createElement('button');del.textContent='删除';del.onclick=function(){var arr=store.get('logs')||[];var idx=arr.findIndex(function(x){return x.date===lg.date && x.title===lg.title});if(idx>=0){arr.splice(idx,1);store.set('logs',arr);renderTimeline();renderLogs();renderSummary();renderProfilePreview()}};right.appendChild(del);li.appendChild(left);li.appendChild(main);li.appendChild(tags);li.appendChild(right);wrap.appendChild(li)})}
  function bindCopy(){var btn=byId('copy-output');if(!btn)return;btn.onclick=function(){var text=(byId('gen-output').textContent||'');if(!text)return;try{navigator.clipboard.writeText(text).then(function(){btn.textContent='已复制';setTimeout(function(){btn.textContent='复制生成内容'},1200);tip('已复制')})}catch(e){}}}
  function init(){ensure();migrate();try{JSON.parse(localStorage.getItem('sj_records')||'null')}catch(e){localStorage.setItem('sj_records',JSON.stringify([]))};bindTheme();bindProfile();bindExp();bindHobby();bindLog();renderHobbies();renderLogs();bindStatus();renderStatus();bindGoal();renderGoals();bindGen();bindOpenShare();renderSummary();bindCopy();renderProfilePreview();renderUserOverview();renderUserMini();renderTimeline();window.addEventListener('storage',function(e){if(e && e.key==='sj_records'){renderProfilePreview();renderUserOverview()}})}
  function expose(){try{window.toggleTheme=toggleTheme;window.saveProfile=saveProfileFn;var s=byId('init-status');if(s)s.textContent='已就绪'}catch(e){}}
  document.addEventListener('DOMContentLoaded',function(){var slots=document.querySelectorAll('.slogan');var sg='成就日常，清谈有趣';try{var raw=localStorage.getItem('pg_slogan');if(raw){var parsed=JSON.parse(raw);if(typeof parsed==='string')sg=parsed}}catch(e){}slots.forEach(function(el){el.textContent=sg})})
  document.addEventListener('DOMContentLoaded',expose)
  document.addEventListener('DOMContentLoaded',init)
})();
